export interface HiAIConfig {
  appId: string;
  apiKey: string;
  clientSecret: string;
  packageName: string;
}

export const HIAI_CONFIG: HiAIConfig = {
  appId: '6917605309959973739',
  apiKey: 'DgEDAJJSMJjegWH5WYUJ7HyZVu6HyA40uv2XYYfSGn8R9Hg+Ut1yCTCc50EjuA+9p+eHIq0AOutiYIbvi2+9iorUzKgQXNjix8XF/A==',
  clientSecret: 'cce77fec1f2f575034eb05e08fd012e212fec594d1fb261bb5599d073a9fe281',
  packageName: 'com.example.harmonyhealthcare'
};
