import request from '@/utils/request'

export default {
  getDoctorInfo(userId) { return request.get('/doctor-portal/info', { params: { userId } }) },
  getPatients(doctorId, params) { return request.get('/doctor-portal/patients', { params: { doctorId, ...params } }) },
  getPatientGroups(doctorId) { return request.get('/doctor-portal/patient-groups', { params: { doctorId } }) },
  createPatientGroup(data) { return request.post('/doctor-portal/patient-group', data) },
  deletePatientGroup(id) { return request.delete(`/doctor-portal/patient-group/${id}`) },
  addPatientToGroup(data) { return request.post('/doctor-portal/patient-group/add-patient', data) },
  removePatientFromGroup(groupId, patientId) { return request.delete('/doctor-portal/patient-group/remove-patient', { params: { groupId, patientId } }) },
  getAppointments(doctorId, params) { return request.get('/doctor-portal/appointments', { params: { doctorId, ...params } }) },
  getTransfers(userId, params) { return request.get('/doctor-portal/transfers', { params: { userId, ...params } }) },
  approveTransfer(id) { return request.post(`/doctor-portal/transfer/approve/${id}`) },
  rejectTransfer(id, data) { return request.post(`/doctor-portal/transfer/reject/${id}`, data) },
  approveAppointment(id) { return request.post(`/doctor-portal/appointment/approve/${id}`) },
  rejectAppointment(id, data) { return request.post(`/doctor-portal/appointment/reject/${id}`, data) },
  postponeAppointment(id, data) { return request.post(`/doctor-portal/appointment/postpone/${id}`, data) },
  createTransfer(data) { return request.post('/doctor-portal/transfer/create', data) },
  cancelTransfer(id) { return request.post(`/doctor-portal/transfer/cancel/${id}`) },
  getHospitalDoctors(hospitalId) { return request.get('/doctor-portal/hospital-doctors', { params: { hospitalId } }) },
  getMedicalRecords(doctorId, params) { return request.get('/doctor-portal/medical-records', { params: { doctorId, ...params } }) },
  createMedicalRecord(data) { return request.post('/doctor-portal/medical-record', data) },
  updateMedicalRecord(id, data) { return request.put(`/doctor-portal/medical-record/${id}`, data) },
  getMedicationRecords(patientId, params) { return request.get('/doctor-portal/medication-records', { params: { patientId, ...params } }) },
  createMedicationRecord(data) { return request.post('/doctor-portal/medication-record', data) },
  updateMedicationRecord(id, data) { return request.put(`/doctor-portal/medication-record/${id}`, data) },
  getPrescriptions(doctorId, params) { return request.get('/doctor-portal/prescriptions', { params: { doctorId, ...params } }) },
  createPrescription(data) { return request.post('/doctor-portal/prescription', data) },
  getStatistics(doctorId) { return request.get('/doctor-portal/statistics', { params: { doctorId } }) },
  recoverPatient(patientId, doctorId) { return request.post(`/doctor-portal/patient/recover/${patientId}`, null, { params: { doctorId } }) },
  getRecoveryRequests(doctorId) { return request.get('/doctor-portal/recovery-requests', { params: { doctorId } }) },
  approveRecoveryRequest(id) { return request.post(`/doctor-portal/recovery-request/approve/${id}`) },
  rejectRecoveryRequest(id) { return request.post(`/doctor-portal/recovery-request/reject/${id}`) },
  getHospitals(keyword) { return request.get('/doctor-portal/hospitals', { params: { keyword } }) }
}
