server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medical_health?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  thymeleaf:
    enabled: false
  # Swagger 3.0.0 与 Spring Boot 2.7.x 兼容性配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 文件上传大小限制（解决3D模型/视频上传报错）
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  tomcat:
    max-http-post-size: -1

# MyBatis-Plus
mybatis-plus:
  type-aliases-package: com.example.medical.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传配置（你本地3D模型/视频存放路径）
file:
  upload-path: D:/harmony-health-care/uploads/
