CREATE TABLE IF NOT EXISTS `examination_report` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `appointment_id` bigint DEFAULT NULL COMMENT '关联挂号ID',
  `hospital_id` bigint DEFAULT NULL COMMENT '医院ID',
  `doctor_id` bigint DEFAULT NULL COMMENT '医生ID',
  `report_type` varchar(50) DEFAULT NULL COMMENT '报告类型：CT检查/X光片/MRI核磁共振/血常规/尿常规/心电图/B超/生化全项',
  `report_name` varchar(100) DEFAULT NULL COMMENT '报告名称',
  `exam_date` date DEFAULT NULL COMMENT '检查日期',
  `department_name` varchar(50) DEFAULT NULL COMMENT '科室名称',
  `doctor_name` varchar(50) DEFAULT NULL COMMENT '医生姓名',
  `hospital_name` varchar(100) DEFAULT NULL COMMENT '医院名称',
  `pickup_location` varchar(200) DEFAULT NULL COMMENT '取片位置/窗口号',
  `print_status` int DEFAULT 0 COMMENT '打印状态：0-待打印 1-打印中 2-已完成可取',
  `result_status` int DEFAULT 0 COMMENT '结果状态：0-待出结果 1-已出结果',
  `conclusion` varchar(500) DEFAULT NULL COMMENT '检查结论',
  `abnormal_items` varchar(200) DEFAULT NULL COMMENT '异常项描述',
  `print_time` datetime DEFAULT NULL COMMENT '打印完成时间',
  `result_time` datetime DEFAULT NULL COMMENT '结果出具时间',
  `fee` decimal(10,2) DEFAULT 0.00 COMMENT '检查费用',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` int DEFAULT 0 COMMENT '逻辑删除：0-未删除 1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_appointment_id` (`appointment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='检验检查报告表';
